# Generated by Django 3.1.1 on 2020-09-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200902_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='CategoryToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.subcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sub_category',
            field=models.ManyToManyField(through='company.CategoryToCompany', to='company.SubCategory'),
        ),
    ]
