# Generated by Django 3.1.1 on 2020-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200902_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.URLField(max_length=3000, null=True),
        ),
    ]
