# Generated by Django 3.1.1 on 2020-09-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200903_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryToSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('payroll', models.IntegerField()),
                ('category', models.ManyToManyField(through='company.CategoryToSalary', to='company.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='categorytosalary',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.salary'),
        ),
    ]
