# Generated by Django 3.1.1 on 2020-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200905_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
