# Generated by Django 3.1.1 on 2020-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longtitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
