# Generated by Django 3.0.3 on 2020-09-10 16:30

from django.db import migrations, models
import django.db.models.deletion
import resume.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'foreign_language',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[resume.functions.Validate_title])),
                ('writer_name', models.CharField(max_length=100, validators=[resume.functions.Validate_writername])),
                ('email', models.CharField(max_length=100, validators=[resume.functions.Validate_email])),
                ('phone_number', models.CharField(max_length=100, validators=[resume.functions.Validate_phone_number])),
                ('description', models.TextField(null=True)),
                ('completion_status', models.CharField(max_length=100, null=True)),
                ('is_fileupload', models.BooleanField()),
                ('fileurl', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='user.UserInformation')),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='resume.Resume')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='LanguageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=100, null=True)),
                ('score', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('foreignlanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_test', to='resume.ForeignLanguage')),
            ],
            options={
                'db_table': 'language_tests',
            },
        ),
        migrations.AddField(
            model_name='foreignlanguage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_language', to='resume.Resume'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('research_content', models.CharField(max_length=1000, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_attending', models.BooleanField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.Resume')),
            ],
            options={
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_incumbent', models.BooleanField(null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='resume.Resume')),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='AwardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=800, null=True)),
                ('date', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_history', to='resume.Resume')),
            ],
            options={
                'db_table': 'award_histories',
            },
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment', to='resume.Career')),
            ],
            options={
                'db_table': 'accomplishments',
            },
        ),
    ]
