# Generated by Django 3.0.3 on 2020-09-08 05:15

from django.db import migrations, models
import resume.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'accomplishments',
            },
        ),
        migrations.CreateModel(
            name='AwardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=800, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'award_histories',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_incumbent', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('research_content', models.CharField(max_length=1000, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_attending', models.BooleanField()),
            ],
            options={
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'foreign_language',
            },
        ),
        migrations.CreateModel(
            name='LanguageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=100, null=True)),
                ('score', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'language_tests',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[resume.functions.Validate_title])),
                ('writer_name', models.CharField(max_length=100, validators=[resume.functions.Validate_writername])),
                ('email', models.CharField(max_length=100, validators=[resume.functions.Validate_email])),
                ('phone_number', models.CharField(max_length=100, validators=[resume.functions.Validate_phone_number])),
                ('description', models.TextField(null=True)),
                ('completion_status', models.CharField(max_length=100, null=True)),
                ('is_fileupload', models.BooleanField()),
                ('fileurl', models.URLField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
    ]
