# Generated by Django 3.0.3 on 2020-09-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='user.UserInformation'),
        ),
        migrations.AddField(
            model_name='link',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='languagetest',
            name='foreignlanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_test', to='resume.ForeignLanguage'),
        ),
        migrations.AddField(
            model_name='foreignlanguage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_language', to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='career',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='awardhistory',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_history', to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment', to='resume.Career'),
        ),
    ]
