# Generated by Django 3.0.3 on 2020-09-08 05:15

from django.db import migrations, models
import django.db.models.deletion
import user.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_auto_20200903_0005'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, validators=[user.validator.Validate_email])),
                ('platform_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100, unique=True, validators=[user.validator.Validate_phonenumber])),
                ('password', models.CharField(max_length=100, validators=[user.validator.Validate_password])),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='user.UserAccount')),
            ],
            options={
                'db_table': 'user_information',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
        migrations.CreateModel(
            name='SuggestionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('process_status', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
            options={
                'db_table': 'suggest_status',
            },
        ),
        migrations.CreateModel(
            name='Recomender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
            options={
                'db_table': 'recomenders',
            },
        ),
        migrations.CreateModel(
            name='MatchUpInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_group', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('career_year', models.IntegerField(null=True)),
                ('is_developer', models.BooleanField(null=True)),
                ('education', models.CharField(max_length=500, null=True)),
                ('company', models.CharField(max_length=500, null=True)),
                ('user_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
            options={
                'db_table': 'match_up_information',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('matchup_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MatchUpInformation')),
            ],
            options={
                'db_table': 'jobskills',
            },
        ),
        migrations.CreateModel(
            name='CompanyException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
            options={
                'db_table': 'company_exceptions',
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_status', models.CharField(max_length=200)),
                ('recommendation', models.CharField(max_length=200, null=True)),
                ('is_compensation', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_company', to='position.Position')),
                ('logo_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logo', to='position.Position')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_position', to='position.Position')),
                ('user_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInformation')),
            ],
            options={
                'db_table': 'application_status',
            },
        ),
    ]
